import { createSlice } from '@reduxjs/toolkit';

export const missionsSlice = createSlice({
  name: 'missions',
  initialState: [
    { id: 1, title: 'Posséder 1 produit', completed: false, gain:5 },
    { id: 2, title: 'Posséder 3 produits', completed: false, gain:5 },
    { id: 3, title: 'Posséder 5 produit', completed: false, gain:5 },
    { id: 4, title: 'Posséder 10 produit', completed: false, gain:5 },
    { id: 5, title: 'Posséder 20 produits', completed: false, gain:5 },
    { id: 6, title: 'Posséder 1 produit haut de gamme', completed: false, gain:5 },
    { id: 7, title: 'Posséder 3 produit haut de gamme', completed: false, gain:5 },
    { id: 8, title: 'Posséder 5 produit haut de gamme', completed: false, gain:5 },
    { id: 9, title: 'Posséder 10 produit haut de gamme', completed: false, gain:5 },
    { id: 10, title: 'Acheter 1 licence pour vendre un produit exclusif', completed: false, gain:5 },
    { id: 11, title: 'Acheter 3 licence pour vendre un produit exclusif', completed: false, gain:5 },
    { id: 12, title: 'Acheter 5 licence pour vendre un produit exclusif', completed: false, gain:5 },
    { id: 13, title: 'Acheter 10 licence pour vendre un produit exclusif', completed: false, gain:5 },
    { id: 14, title: 'Ouvrir 1 boutique', completed: false, gain:5 },
    { id: 15, title: 'Ouvrir 2 boutique', completed: false, gain:5 },
    { id: 16, title: 'Ouvrir 3 boutique', completed: false, gain:5 },
    { id: 17, title: 'Ouvrir 5 boutique', completed: false, gain:5 },
    { id: 18, title: 'Avoir 1 super boutique', completed: false, gain:5 },
    { id: 19, title: 'Avoir 2 super boutiques', completed: false, gain:5 },
    { id: 20, title: 'Avoir 3 super boutiques', completed: false, gain:5 },
    { id: 21, title: 'Avoir 1 mega boutique', completed: false, gain:5 },
    { id: 22, title: 'Avoir 2 mega boutiques', completed: false, gain:5 },
    { id: 23, title: 'Avoir 3 mega boutiques', completed: false, gain:5 },
    { id: 24, title: 'Lancer 1 publicité', completed: false, gain:5 },
    { id: 25, title: 'Lancer 3 publicité', completed: false, gain:5 },
    { id: 26, title: 'Lancer 5 publicité', completed: false, gain:5 },
    { id: 27, title: 'Lancer 10 publicité', completed: false, gain:5 },
    { id: 28, title: 'Lancer 20 publicité', completed: false, gain:5 },
    { id: 29, title: 'Utiliser un influenceur 1 fois', completed: false, gain:5 },
    { id: 30, title: 'Utiliser un influenceur 3 fois', completed: false, gain:5 },
    { id: 31, title: 'Utiliser un influenceur 5 fois', completed: false, gain:5 },
    { id: 32, title: 'Utiliser un influenceur 10 fois', completed: false, gain:5 },
    { id: 33, title: 'Faire 1 super publicité', completed: false, gain:5 },
    { id: 34, title: 'Faire 5 super publicités', completed: false, gain:5 },
    { id: 35, title: 'Faire 10 super publicités', completed: false, gain:5 },
    { id: 36, title: 'Faire 1 publicités iconique', completed: false, gain:5 },
    { id: 37, title: 'Faire 5 publicités iconique', completed: false, gain:5 },
    { id: 38, title: 'Atteindre un bénéfice de 200$ sur une journée', completed: false, gain:5 },
    { id: 39, title: 'Atteindre un bénéfice de 2000$ sur une journée', completed: false, gain:5 },
    { id: 40, title: 'Atteindre un bénéfice de 20000$ sur une journée', completed: false, gain:5 },
    { id: 41, title: 'Atteindre un bénéfice de 1000$ sur une semaine', completed: false, gain:5 },
    { id: 42, title: 'Atteindre un bénéfice de 10000$ sur une semaine', completed: false, gain:5 },
    { id: 43, title: 'Atteindre un bénéfice de 100000$ sur une semaine', completed: false, gain:5 },
    { id: 44, title: 'Atteindre un bénéfice de 5000$ sur un mois', completed: false, gain:5 },
    { id: 45, title: 'Atteindre un bénéfice de 50000$ sur un mois', completed: false, gain:5 },
    { id: 46, title: 'Atteindre un bénéfice de 500000$ sur un mois', completed: false, gain:5 },
    { id: 47, title: 'Gérer 1 incident', completed: false, gain:5 },
    { id: 48, title: 'Gérer 3 incidents', completed: false, gain:5 },
    { id: 49, title: 'Gérer 5 incidents', completed: false, gain:5 },
    { id: 50, title: 'Gérer 10 incidents', completed: false, gain:5 },
    { id: 51, title: 'Atteindre 50 clients dans une journée', completed: false, gain:5 },
    { id: 52, title: 'Atteindre 100 clients dans une journée', completed: false, gain:5 },
    { id: 53, title: 'Atteindre 500 clients dans une journée', completed: false, gain:5 },
    { id: 54, title: 'Atteindre 1000 clients dans une journée', completed: false, gain:5 },
    { id: 55, title: 'Recruter 1 employé pour une même boutique', completed: false, gain:5 },
    { id: 56, title: 'Recruter 3 employé pour une même boutique', completed: false, gain:5 },
    { id: 57, title: 'Recruter 5 employé pour une même boutique', completed: false, gain:5 },
    { id: 58, title: 'Recruter 10 employé pour une même boutique', completed: false, gain:5 },
    { id: 59, title: 'Atteindre 1000 likes sur les réseaux sociaux pour une boutique', completed: false, gain:5 },
    { id: 60, title: 'Atteindre 10000 likes sur les réseaux sociaux pour une boutique', completed: false, gain:5 },
    { id: 61, title: 'Atteindre 50000 likes sur les réseaux sociaux pour une boutique', completed: false, gain:5 },
    { id: 62, title: 'Atteindre 100000 likes sur les réseaux sociaux pour une boutique', completed: false, gain:5 },
    { id: 63, title: 'Atteindre 500000 likes sur les réseaux sociaux pour une boutique', completed: false, gain:5 },
    { id: 64, title: 'Atteindre 1000000 likes sur les réseaux sociaux pour une boutique', completed: false, gain:5 },
    { id: 65, title: 'Atteindre 5000000 likes sur les réseaux sociaux pour une boutique', completed: false, gain:5 },
    { id: 66, title: 'Atteindre 10000000 likes sur les réseaux sociaux pour une boutique', completed: false, gain:5 },    
    { id: 67, title: 'Atteindre 1000 followers  sur les réseaux sociaux pour une boutique', completed: false, gain:5 },
    { id: 68, title: 'Atteindre 10000 followers  sur les réseaux sociaux pour une boutique', completed: false, gain:5 },
    { id: 69, title: 'Atteindre 50000 followers  sur les réseaux sociaux pour une boutique', completed: false, gain:5 },
    { id: 70, title: 'Atteindre 100000 followers  sur les réseaux sociaux pour une boutique', completed: false, gain:5 },
    { id: 71, title: 'Atteindre 500000 followers  sur les réseaux sociaux pour une boutique', completed: false, gain:5 },
    { id: 72, title: 'Atteindre 1000000 followers  sur les réseaux sociaux pour une boutique', completed: false, gain:5 },
    { id: 73, title: 'Atteindre 5000000 followers  sur les réseaux sociaux pour une boutique', completed: false, gain:5 },
    { id: 74, title: 'Atteindre 10000000 followers  sur les réseaux sociaux pour une boutique', completed: false, gain:5 },
    { id: 75, title: 'Lancer 1 publicité à la télévision', completed: false, gain:5 },
    { id: 76, title: 'Lancer 3 publicités à la télévision', completed: false, gain:5 },
    { id: 77, title: 'Lancer 5 publicités à la télévision', completed: false, gain:5 },
    { id: 78, title: 'Lancer 10 publicités à la télévision', completed: false, gain:5 },
    { id: 79, title: 'Ameliorer le temps de livraison 1 fois', completed: false, gain:5 },
    { id: 80, title: 'Ameliorer le temps de livraison 3 fois', completed: false, gain:5 },
    { id: 81, title: 'Ameliorer le temps de livraison 5 fois', completed: false, gain:5 },
    { id: 82, title: 'Ameliorer le temps de livraison 10 fois', completed: false, gain:5 },
    { id: 83, title: 'Ameliorer le packaging des produits 1 fois', completed: false, gain:5 },
    { id: 84, title: 'Ameliorer le packaging des produits 3 fois', completed: false, gain:5 },
    { id: 85, title: 'Ameliorer le packaging des produits 5 fois', completed: false, gain:5 },
    { id: 86, title: 'Ameliorer le packaging des produits 10 fois', completed: false, gain:5 },
    { id: 87, title: 'Ameliorer un employé 1 fois', completed: false, gain:5 },
    { id: 88, title: 'Ameliorer un employé 3 fois', completed: false, gain:5 },
    { id: 89, title: 'Ameliorer un employé 5 fois', completed: false, gain:5 },
    { id: 90, title: 'Ameliorer un employé 10 fois', completed: false, gain:5 },
    { id: 91, title: 'Avoir une moyenne parfaite sur 1 boutique', completed: false, gain:5 },
    { id: 92, title: 'Avoir une moyenne parfaite sur 3 boutiques', completed: false, gain:5 },
    { id: 93, title: 'Avoir une moyenne parfaite sur 5 boutiques', completed: false, gain:5 },
    { id: 94, title: 'Avoir une moyenne parfaite sur 10 boutiques', completed: false }
  ],
  reducers: {
    completeMission: (state, action) => {
      const mission = state.find((m) => m.id === action.payload);
      if (mission) {
        mission.completed = true;
      }
    },
  },
});

export const { completeMission } = missionsSlice.actions;

export default missionsSlice.reducer;